// @ts-check
import process from "node:process";
import { flagString } from "../lib/args.js";
import { c } from "../lib/colors.js";
import { suggest } from "../lib/suggest.js";
import { sequence } from "../lib/gates.js";

// The CI surface, GENERATED from the gate declaration (audit finding F1).
//
// `action.yml` used to be a fourth hand-maintained list of gates, beside
// `close`'s array and `doctor`'s rows. Nothing noticed when they diverged,
// so a gate could be in the close and absent from CI for a release — which
// is exactly what happened to the runtime checks.
//
// The action stays VERSIONED rather than generated on demand: a project that
// writes `uses: GCarin1/Doctrina@v1` has no CLI to generate it with, and a
// composite action that only exists after an npm install is not an action.
// So this command emits it, and a drift test holds the committed file to
// what this emits — the same pattern the AGENTS.md surface block uses.

const TARGETS = ["github"];

// Flags this command accepts. Declared HERE, with the command, so
// adding a command never requires editing the entrypoint.
export const flags = { boolean: ["json"], string: ["emit"] };

export async function run(_positional, flags) {
  const target = flagString(flags, "emit", "");
  if (!target) {
    console.error(c.red("error:") + " ci requires --emit <target>");
    console.error(c.gray("hint: ") + `available targets: ${TARGETS.join(", ")}`);
    return 2;
  }
  if (!TARGETS.includes(target)) {
    console.error(c.red("error:") + ` unknown CI target "${target}"`);
    const guess = suggest(target, TARGETS);
    console.error(c.gray("hint: ") + (guess ? `did you mean --emit ${guess}?` : `available: ${TARGETS.join(", ")}`));
    return 2;
  }
  process.stdout.write(emitGithub());
  return 0;
}

/**
 * The composite action, rendered from SEQUENCES.ci.
 *
 * Takes the sequence as a parameter so a test can prove the surface follows
 * the DECLARATION rather than a copy of it: add a step to the array passed
 * in, and it appears in the YAML with no edit here.
 */
export function emitGithub(steps = sequence("ci")) {
  // Two renderings of the same list: the file header says what each gate
  // checks, the action's description just names them.
  const gateSummaries = steps.map((s) => s.summary ?? s.label.replace(/^doctrina /, ""));
  const gateNames = steps.map((s) => s.short ?? s.label.replace(/^doctrina /, "")).join(", ");
  const out = [];

  out.push("# Reusable composite action: run the Doctrina gates in CI.");
  out.push("#");
  out.push("#   - uses: GCarin1/Doctrina@main        # or a released tag");
  out.push("#     with:");
  out.push("#       strict: \"true\"                   # coverage/trace as hard gates");
  out.push("#");
  out.push("# GENERATED by `doctrina ci --emit github` from SEQUENCES.ci in");
  out.push("# packages/doctrina-cli/src/lib/gates.js — the one declaration `close` and");
  out.push("# `doctor` also read. Edit the declaration, re-emit, and commit; a drift");
  out.push("# test fails when this file and the declaration disagree.");
  out.push("#");
  for (const line of wrapComment(`The gates: ${gateSummaries.join(", ")}.`, 74)) out.push(`# ${line}`);
  out.push("#");
  out.push("# `run-prefix` exists so this repository can dogfood the action against its");
  out.push("# own working tree instead of the published package.");
  out.push("name: \"Doctrina gates\"");
  out.push(`description: "Run the Doctrina gates (${gateNames}) against a project's .doctrina/ tree."`);
  out.push("branding:");
  out.push("  icon: \"check-circle\"");
  out.push("  color: \"purple\"");
  out.push("");
  out.push("inputs:");
  out.push("  strict:");
  out.push("    description: \"Run coverage and trace with --strict (fail on any gap). Set to 'false' for report-only.\"");
  out.push("    required: false");
  out.push("    default: \"true\"");
  out.push("  version:");
  out.push("    description: \"doctrina-cli version to run via npx (ignored when run-prefix is set).\"");
  out.push("    required: false");
  out.push("    default: \"latest\"");
  out.push("  working-directory:");
  out.push("    description: \"Directory holding the .doctrina/ tree.\"");
  out.push("    required: false");
  out.push("    default: \".\"");
  out.push("  run-prefix:");
  out.push("    description: \"Override the command used to invoke the CLI (e.g. 'node packages/doctrina-cli/src/index.js' for this repo's own CI).\"");
  out.push("    required: false");
  out.push("    default: \"\"");
  out.push("");
  out.push("runs:");
  out.push("  using: \"composite\"");
  out.push("  steps:");
  out.push("    - name: Resolve CLI invocation");
  out.push("      id: cli");
  out.push("      shell: bash");
  out.push("      working-directory: ${{ inputs.working-directory }}");
  out.push("      run: |");
  out.push("        PREFIX=\"${{ inputs.run-prefix }}\"");
  out.push("        if [ -z \"$PREFIX\" ]; then PREFIX=\"npx --yes doctrina-cli@${{ inputs.version }}\"; fi");
  out.push("        echo \"prefix=$PREFIX\" >> \"$GITHUB_OUTPUT\"");

  const prefix = "${{ steps.cli.outputs.prefix }}";
  for (const step of steps) {
    out.push("");
    if (step.why) {
      for (const line of step.why.split("\n")) out.push(`    # ${line}`.trimEnd());
    }
    out.push(`    - name: ${step.label}`);
    out.push("      shell: bash");
    out.push("      working-directory: ${{ inputs.working-directory }}");

    const command = `${prefix} ${(step.argv ?? []).join(" ")}`.trim();
    if (step.script) {
      out.push("      run: |");
      for (const line of step.script.replaceAll("{{PREFIX}}", prefix).split("\n")) {
        out.push(`        ${line}`.trimEnd());
      }
    } else if (step.strict) {
      // The one shape the declaration cannot flatten to a single line: the
      // action's `strict` input decides whether the gate fails on a gap or
      // only reports it, and an adopting project in its backfill phase needs
      // the report-only half.
      out.push("      run: |");
      out.push("        if [ \"${{ inputs.strict }}\" = \"true\" ]; then");
      out.push(`          ${command} --strict`);
      out.push("        else");
      out.push(`          ${command}`);
      out.push("        fi");
    } else {
      out.push(`      run: ${command}`);
    }
  }
  out.push("");
  return out.join("\n");
}

// Wrap prose to a column so the emitted comments read like hand-written ones
// rather than one very long line the reader has to scroll.
function wrapComment(text, width) {
  const out = [];
  let line = "";
  for (const word of text.split(/\s+/)) {
    if (line && (line + " " + word).length > width) {
      out.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) out.push(line);
  return out;
}

export const help = `
Usage: doctrina ci --emit <target>

Emit the CI pipeline for the declared gate sequence, on stdout.

The gates a pipeline runs are declared once, in SEQUENCES.ci
(packages/doctrina-cli/src/lib/gates.js) — the same declaration \`close\`
executes and \`doctor\` reports. This command renders that declaration as CI
configuration, so the pipeline cannot fall behind the sequence the way a
hand-maintained YAML file did.

Targets:
  github    A composite GitHub Action (the repository's own action.yml).

The action stays versioned in the repository: a project that writes
\`uses: <owner>/<repo>@v1\` has no CLI to generate it with. Re-emit after
changing the declaration and commit the result; the drift test compares the
committed file against this output.

Read-only — it writes nothing, so redirect it yourself:
  doctrina ci --emit github > action.yml
`;
