import { OPERATIONS, COMMAND_NAMES } from "../lib/commands.js";
import { c } from "../lib/colors.js";

// Shell completions, generated from the same OPERATIONS catalog that feeds
// `--help` and the docs drift tests — so the completion script can never
// know a different surface than the CLI ships. Static output by design:
// paste it into your shell config once; regenerate after upgrading.

function subcommandMap() {
  const map = new Map();
  for (const [op] of OPERATIONS) {
    const [cmd, sub] = op.split(" ");
    if (!sub) continue;
    if (!map.has(cmd)) map.set(cmd, []);
    map.get(cmd).push(sub);
  }
  return map;
}

function bashScript() {
  const subs = subcommandMap();
  const cases = [...subs.entries()]
    .map(([cmd, list]) => `    ${cmd}) COMPREPLY=( $(compgen -W "${list.join(" ")}" -- "$cur") );;`)
    .join("\n");
  return `# doctrina bash completion — generated by \`doctrina completion bash\`
# Install: doctrina completion bash >> ~/.bashrc   (or into bash_completion.d)
_doctrina() {
  local cur
  cur="\${COMP_WORDS[COMP_CWORD]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${COMMAND_NAMES.join(" ")}" -- "$cur") )
    return
  fi
  if [ "$COMP_CWORD" -eq 2 ]; then
    case "\${COMP_WORDS[1]}" in
${cases}
    esac
  fi
}
complete -F _doctrina doctrina
`;
}

function zshScript() {
  const subs = subcommandMap();
  const cases = [...subs.entries()]
    .map(([cmd, list]) => `    ${cmd}) _values 'subcommand' ${list.map((s) => `'${s}'`).join(" ")} ;;`)
    .join("\n");
  return `#compdef doctrina
# doctrina zsh completion — generated by \`doctrina completion zsh\`
# Install: doctrina completion zsh > "\${fpath[1]}/_doctrina"   (then restart zsh)
_doctrina() {
  if (( CURRENT == 2 )); then
    _values 'command' ${COMMAND_NAMES.map((n) => `'${n}'`).join(" ")}
    return
  fi
  case "\${words[2]}" in
${cases}
  esac
}
_doctrina "$@"
`;
}

function pwshScript() {
  const subs = subcommandMap();
  const entries = [...subs.entries()]
    .map(([cmd, list]) => `  "${cmd}" = @(${list.map((s) => `"${s}"`).join(", ")})`)
    .join("\n");
  return `# doctrina PowerShell completion — generated by \`doctrina completion pwsh\`
# Install: doctrina completion pwsh >> $PROFILE   (then restart the shell)
$doctrinaCommands = @(${COMMAND_NAMES.map((n) => `"${n}"`).join(", ")})
$doctrinaSubcommands = @{
${entries}
}
Register-ArgumentCompleter -Native -CommandName doctrina -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
  if ($words.Count -le 1 -or ($words.Count -eq 2 -and $wordToComplete)) {
    $doctrinaCommands | Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    return
  }
  $cmd = $words[1]
  if ($doctrinaSubcommands.ContainsKey($cmd)) {
    $doctrinaSubcommands[$cmd] | Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
  }
}
`;
}

export async function run(positional, _flags) {
  const shell = positional[0];
  const generators = { bash: bashScript, zsh: zshScript, pwsh: pwshScript, powershell: pwshScript };
  if (!shell || !generators[shell]) {
    console.error(c.red("error:") + ` completion requires a shell: bash, zsh, or pwsh${shell ? ` (got "${shell}")` : ""}`);
    console.error(c.gray("hint: ") + "`doctrina completion bash >> ~/.bashrc`");
    return 2;
  }
  process.stdout.write(generators[shell]());
  return 0;
}

export const help = `
Usage: doctrina completion <bash|zsh|pwsh>

Print a shell-completion script for the doctrina CLI, generated from
the same operation catalog that feeds --help (commands and their
subcommands; flags are not completed). Static output — install once,
regenerate after upgrading:

  doctrina completion bash >> ~/.bashrc
  doctrina completion zsh  > "\${fpath[1]}/_doctrina"
  doctrina completion pwsh >> $PROFILE
`;
